In [1]:
import pandas as pd 
import numpy as np

In [3]:
count_df = pd.read_csv('../QC_modules/BIOS2931_qc_filtered/counts_qc_passed.csv', index_col=0)
map_df = pd.read_csv('../QC_modules/BIOS2931_qc_filtered/mapped_qc_passed.csv', index_col = 0)

In [5]:
count_df.columns

Index(['MCF7_AZD_0p1uM-1', 'MCF7_AZD_0p1uM-2', 'MCF7_AZD_0p1uM-3',
       'MCF7_AZD_10uM-1', 'MCF7_AZD_10uM-2', 'MCF7_AZD_10uM-3',
       'MCF7_AZD_1uM-1', 'MCF7_AZD_1uM-2', 'MCF7_AZD_1uM-3',
       'MCF7_DACTO_0p1uM-1',
       ...
       'MDA_TOR2_1uM-3', 'MDA_ZOTA_0p1uM-1', 'MDA_ZOTA_0p1uM-2',
       'MDA_ZOTA_0p1uM-3', 'MDA_ZOTA_10uM-1', 'MDA_ZOTA_10uM-2',
       'MDA_ZOTA_10uM-3', 'MDA_ZOTA_1uM-1', 'MDA_ZOTA_1uM-2',
       'MDA_ZOTA_1uM-3'],
      dtype='object', length=249)

In [18]:
sample_name = pd.DataFrame(data= count_df.columns, columns=['sample_name'])
sample_name['sample'] = sample_name['sample_name'].str.split('_').str[0]
sample_name['compound'] = sample_name['sample_name'].str.split('_').str[1].str.split('-').str[0]
sample_name['dose'] = sample_name['sample_name'].str.split('_').str[2].str.split('-').str[0]

sample_name

          sample_name sample compound   dose
0    MCF7_AZD_0p1uM-1   MCF7      AZD  0p1uM
1    MCF7_AZD_0p1uM-2   MCF7      AZD  0p1uM
2    MCF7_AZD_0p1uM-3   MCF7      AZD  0p1uM
3     MCF7_AZD_10uM-1   MCF7      AZD   10uM
4     MCF7_AZD_10uM-2   MCF7      AZD   10uM
..                ...    ...      ...    ...
244   MDA_ZOTA_10uM-2    MDA     ZOTA   10uM
245   MDA_ZOTA_10uM-3    MDA     ZOTA   10uM
246    MDA_ZOTA_1uM-1    MDA     ZOTA    1uM
247    MDA_ZOTA_1uM-2    MDA     ZOTA    1uM
248    MDA_ZOTA_1uM-3    MDA     ZOTA    1uM

[249 rows x 4 columns]

In [11]:
sample_name['sample'].value_counts()

sample
MCF7    129
MDA     120
Name: count, dtype: int64

In [16]:
sample_name['dose'].value_counts()

dose
0p1uM    75
10uM     75
1uM      75
Name: count, dtype: int64

In [ ]:
sample_name[sample_name['compound'].str.contains('DMSO')].head(2)

In [17]:
sample_name[sample_name['compound'].str.contains('DMSO')].head(2)

     sample_name sample compound dose
18  MCF7_DMSO1-1   MCF7  DMSO1-1  NaN
19  MCF7_DMSO1-2   MCF7  DMSO1-2  NaN

In [19]:
sample_name['compound'].value_counts()

compound
AZD      18
DACTO    18
EVE      18
KU       18
LY       18
OSI      18
RAPA     18
RIDA     18
TEMSI    18
TOR1     18
TOR2     18
ZOTA     18
DMSO1    12
DMSO2    12
WYE       9
Name: count, dtype: int64

## create an annotation file for DEG

In [21]:
# sample name, rep number, plate, concentration 

annot = pd.DataFrame(data= count_df.columns, columns=['sample_name'])
annot['sample'] = annot['sample_name'].str.split('_').str[0]
annot['compound'] = annot['sample_name'].str.split('_').str[1].str.split('-').str[0]
annot['dose'] = annot['sample_name'].str.split('_').str[2].str.split('-').str[0]
annot['replicate'] = annot['sample_name'].str.split('-').str[-1]
annot

          sample_name sample compound   dose replicate
0    MCF7_AZD_0p1uM-1   MCF7      AZD  0p1uM         1
1    MCF7_AZD_0p1uM-2   MCF7      AZD  0p1uM         2
2    MCF7_AZD_0p1uM-3   MCF7      AZD  0p1uM         3
3     MCF7_AZD_10uM-1   MCF7      AZD   10uM         1
4     MCF7_AZD_10uM-2   MCF7      AZD   10uM         2
..                ...    ...      ...    ...       ...
244   MDA_ZOTA_10uM-2    MDA     ZOTA   10uM         2
245   MDA_ZOTA_10uM-3    MDA     ZOTA   10uM         3
246    MDA_ZOTA_1uM-1    MDA     ZOTA    1uM         1
247    MDA_ZOTA_1uM-2    MDA     ZOTA    1uM         2
248    MDA_ZOTA_1uM-3    MDA     ZOTA    1uM         3

[249 rows x 5 columns]

In [22]:
annot[annot['sample_name'].str.contains('DMSO')]

      sample_name sample compound dose replicate
18   MCF7_DMSO1-1   MCF7    DMSO1  NaN         1
19   MCF7_DMSO1-2   MCF7    DMSO1  NaN         2
20   MCF7_DMSO1-3   MCF7    DMSO1  NaN         3
21   MCF7_DMSO1-4   MCF7    DMSO1  NaN         4
22   MCF7_DMSO1-5   MCF7    DMSO1  NaN         5
23   MCF7_DMSO1-6   MCF7    DMSO1  NaN         6
24   MCF7_DMSO2-1   MCF7    DMSO2  NaN         1
25   MCF7_DMSO2-2   MCF7    DMSO2  NaN         2
26   MCF7_DMSO2-3   MCF7    DMSO2  NaN         3
27   MCF7_DMSO2-4   MCF7    DMSO2  NaN         4
28   MCF7_DMSO2-5   MCF7    DMSO2  NaN         5
29   MCF7_DMSO2-6   MCF7    DMSO2  NaN         6
147   MDA_DMSO1-1    MDA    DMSO1  NaN         1
148   MDA_DMSO1-2    MDA    DMSO1  NaN         2
149   MDA_DMSO1-3    MDA    DMSO1  NaN         3
150   MDA_DMSO1-4    MDA    DMSO1  NaN         4
151   MDA_DMSO1-5    MDA    DMSO1  NaN         5
152   MDA_DMSO1-6    MDA    DMSO1  NaN         6
153   MDA_DMSO2-1    MDA    DMSO2  NaN         1
154   MDA_DMSO2-2    MDA    DMSO2  NaN         2
155   MDA_DMSO2-3    MDA    DMSO2  NaN         3
156   MDA_DMSO2-4    MDA    DMSO2  NaN         4
157   MDA_DMSO2-5    MDA    DMSO2  NaN         5
158   MDA_DMSO2-6    MDA    DMSO2  NaN         6